// Generated by apps/web/scripts/derive-sockets.ts. Do not edit by hand.
//
// Where each character's weapon hand actually is, read out of its rig and
// expressed as fractions of the fitted character's own bounding box.
//
// This exists because the setup screen renders the unrigged model.glb, which has
// no skeleton to query, and every estimate of that position has been wrong: 0.46
// of height is mid-thigh and hung relics at the leg, and a fixed sign put the
// weapon in the left hand. The rig knows exactly, so the answer is extracted
// once and shipped rather than guessed at runtime.
//
// Fractions rather than world units, so a change to AVATAR_HEIGHT or
// BOSS_HEIGHT does not silently move every weapon.

export interface HandSocketRatios {
  x: number;
  y: number;
  z: number;
  /**
   * Which hand actually holds the weapon.
   *
   * Not always the right one: the image model does not reliably honour "the
   * right hand", and Ember came back with its fist on the left. Nothing in the
   * mesh distinguishes a closed fist from an open one, so this is recorded from
   * the concept rather than detected.
   */
  bone: "LeftHand" | "RightHand";
}

export const HAND_SOCKETS: Record<string, HandSocketRatios> = {
  "ember": { x: -0.4213, y: 0.5716, z: 0.1412, bone: "RightHand" },
  "frost": { x: -0.4309, y: 0.5747, z: 0.1845, bone: "RightHand" },
  "storm": { x: -0.4413, y: 0.5697, z: 0.1916, bone: "RightHand" },
  "ashen-warden": { x: -0.4254, y: 0.5311, z: 0.0875, bone: "RightHand" },
  "drowned-choir": { x: -0.4155, y: 0.572, z: 0.1388, bone: "RightHand" },
  "gilded-husk": { x: -0.4118, y: 0.5948, z: 0.0196, bone: "RightHand" },
  "hollow-sovereign": { x: -0.4194, y: 0.5973, z: 0.138, bone: "RightHand" },
  "rootbound-king": { x: -0.4125, y: 0.578, z: 0.0824, bone: "RightHand" },
};

/**
 * Falls back to the middle of the measured range rather than to nothing, so a
 * character generated after this file was last regenerated still holds its
 * weapon at a plausible height instead of at its feet.
 */
export const DEFAULT_HAND_SOCKET: HandSocketRatios = {
  x: -0.42,
  y: 0.57,
  z: 0.14,
  bone: "RightHand",
};

export function handSocketFor(slug: string): HandSocketRatios {
  return HAND_SOCKETS[slug] ?? DEFAULT_HAND_SOCKET;
}
