// Generated by apps/web/scripts/derive-sockets.ts. Do not edit by hand.
//
// Where each character's weapon hand actually is, read out of its rig and
// expressed as fractions of the fitted character's own bounding box.
//
// This exists because the setup screen renders the unrigged model.glb, which has
// no skeleton to query, and every estimate of that position has been wrong: 0.46
// of height is mid-thigh and hung relics at the leg, and a fixed sign put the
// weapon in the left hand. The rig knows exactly, so the answer is extracted
// once and shipped rather than guessed at runtime.
//
// Fractions rather than world units, so a change to AVATAR_HEIGHT or
// BOSS_HEIGHT does not silently move every weapon.

export interface HandSocketRatios {
  x: number;
  y: number;
  z: number;
  /**
   * Which hand actually holds the weapon.
   *
   * Not always the right one: the image model does not reliably honour "the
   * right hand", and Ember came back with its fist on the left. Nothing in the
   * mesh distinguishes a closed fist from an open one, so this is recorded from
   * the concept rather than detected.
   */
  bone: "LeftHand" | "RightHand";
}

export const HAND_SOCKETS: Record<string, HandSocketRatios> = {
  "ember": { x: -0.4213, y: 0.5716, z: 0.1412, bone: "RightHand" },
  "frost": { x: -0.4309, y: 0.5747, z: 0.1845, bone: "RightHand" },
  "storm": { x: -0.4413, y: 0.5697, z: 0.1916, bone: "RightHand" },
  "ashen-warden": { x: -0.4254, y: 0.5311, z: 0.0875, bone: "RightHand" },
  "drowned-choir": { x: -0.4155, y: 0.572, z: 0.1388, bone: "RightHand" },
  "gilded-husk": { x: -0.4118, y: 0.5948, z: 0.0196, bone: "RightHand" },
  "hollow-sovereign": { x: -0.4194, y: 0.5973, z: 0.138, bone: "RightHand" },
  "rootbound-king": { x: -0.4125, y: 0.578, z: 0.0824, bone: "RightHand" },
};

/**
 * Falls back to the middle of the measured range rather than to nothing, so a
 * character generated after this file was last regenerated still holds its
 * weapon at a plausible height instead of at its feet.
 */
export const DEFAULT_HAND_SOCKET: HandSocketRatios = {
  x: -0.42,
  y: 0.57,
  z: 0.14,
  bone: "RightHand",
};

export function handSocketFor(slug: string): HandSocketRatios {
  return FIST_SOCKETS[slug] ?? HAND_SOCKETS[slug] ?? DEFAULT_HAND_SOCKET;
}

/**
 * Where the closed fist is on the *static* mesh, authored by eye.
 *
 * The generated ratios above cannot answer this, and the reason is worth stating
 * because it cost several rounds to find. Meshy's rigging re-poses a character
 * into a neutral A-pose, arms lowered and hands opened. So the rig knows exactly
 * where a hand is, and it is not the hand the concept drew: the static mesh
 * keeps the raised, closed fist the character was generated with, and the rig
 * has neither the raise nor the fist.
 *
 * That leaves two meshes, each holding half the answer. The setup screen shows
 * the static one, because a closed fist is the whole point of regenerating these
 * characters, so its socket has to be authored rather than measured.
 *
 * Read off each character's concept image as a fraction of its silhouette. These
 * are estimates and expected to need nudging against the screen, which is the
 * honest state of anything derived from looking at a picture.
 */
const FIST_SOCKETS: Record<string, HandSocketRatios> = {
  ember: { x: -0.37, y: 0.75, z: 0.2, bone: "RightHand" },
  frost: { x: -0.4, y: 0.66, z: 0.2, bone: "RightHand" },
  storm: { x: -0.4, y: 0.64, z: 0.2, bone: "RightHand" },
  "ashen-warden": { x: -0.4, y: 0.62, z: 0.18, bone: "RightHand" },
  "drowned-choir": { x: -0.4, y: 0.63, z: 0.18, bone: "RightHand" },
  "gilded-husk": { x: -0.4, y: 0.5, z: 0.14, bone: "RightHand" },
  "rootbound-king": { x: -0.42, y: 0.5, z: 0.14, bone: "RightHand" },
  "hollow-sovereign": { x: -0.4, y: 0.54, z: 0.14, bone: "RightHand" },
};
