import { meshyJson, withRetry } from "./meshy.client.js";
import { CreateTaskResponseSchema } from "./meshy.types.js";

/**
 * Retexture: new surface, same geometry.
 *
 * Ten credits against forty-four for a full generation, and it fits the premise
 * rather than bolting onto it. The shape of a relic is the record of how you
 * fought, so re-tempering it in another element should keep that shape and
 * change only the material. A player who wants a different silhouette has to
 * fight differently, which is the whole point.
 *
 * `enable_original_uv` is on because the input was generated by Meshy and
 * already has a UV layout worth keeping; regenerating one risks moving detail
 * the mesh was built around.
 */
export interface RetextureOptions {
  /** Describes the target material, max 600 characters. */
  stylePrompt: string;
  enablePbr?: boolean;
}

/** POST /openapi/v1/retexture */
export async function createRetexture(
  inputTaskId: string,
  opts: RetextureOptions,
): Promise<string> {
  const raw = await withRetry(() =>
    meshyJson<unknown>("/v1/retexture", {
      method: "POST",
      body: JSON.stringify({
        input_task_id: inputTaskId,
        text_style_prompt: opts.stylePrompt.slice(0, 600),
        ai_model: "meshy-7",
        enable_original_uv: true,
        enable_pbr: opts.enablePbr ?? true,
      }),
    }),
  );
  return CreateTaskResponseSchema.parse(raw).result;
}
