import { Suspense, useEffect, useMemo, useState } from "react";
import { Canvas } from "@react-three/fiber";
import { Environment, OrbitControls, useGLTF } from "@react-three/drei";
import { Group } from "three";
import type { Affinity } from "@relic/core";
import { fitCharacter } from "../lib/characterFit";
import { themeFor } from "../game/theme";

/**
 * Your champion.
 *
 * First person means you never see yourself in the arena, so the character
 * appears where the decision is actually made. Picking "Ember" should show an
 * ember champion turning slowly in front of you, not a word next to an emoji.
 *
 * Falls back to nothing when a model has not been generated, so the affinity
 * screen still works on a fresh clone with an empty storage directory.
 */

const CHAMPION_HEIGHT = 2.6;

function ChampionModel({ slug }: { slug: string }) {
  const { scene } = useGLTF(`/assets/champions/${slug}/model.glb`);
  const model = useMemo(() => scene.clone(true), [scene]);
  const fit = useMemo(() => fitCharacter(model as Group, CHAMPION_HEIGHT), [model]);

  return (
    <group>
      {/*
        fitCharacter stands the model with its feet on y = 0, which is what the
        arena wants. A preview camera aims at the world origin, so left as-is
        the shot frames the character's feet. Lowering the whole rig by half its
        height puts the torso on the camera's aim point.
      */}
      <group position={[0, -CHAMPION_HEIGHT / 2, 0]}>
        <group position={fit.offset} scale={fit.scale}>
          {/* Concepts are framed front-on, so the mesh already faces the camera. */}
          <primitive object={model} />
        </group>
      </group>
    </group>
  );
}

export function ChampionPreview({ affinity }: { affinity: Affinity }) {
  const [available, setAvailable] = useState<boolean | null>(null);
  const theme = themeFor(affinity);
  const slug = affinity === "fire" ? "ember" : affinity === "ice" ? "frost" : "storm";

  useEffect(() => {
    let cancelled = false;
    setAvailable(null);
    fetch(`/assets/champions/${slug}/model.glb`, { method: "HEAD" })
      .then((res) => !cancelled && setAvailable(res.ok))
      .catch(() => !cancelled && setAvailable(false));
    return () => {
      cancelled = true;
    };
  }, [slug]);

  if (available === false) return null;

  return (
    <div className="relative h-[calc(100vh-9rem)] max-h-[46rem] min-h-[26rem] w-full cursor-grab border border-ash-800 bg-ash-900/40 active:cursor-grabbing">
      {available && (
        <Canvas camera={{ position: [0, 0.35, 4.3], fov: 38 }}>
          <ambientLight intensity={0.55} />
          <directionalLight position={[3, 5, 4]} intensity={2.1} />
          <directionalLight position={[-3, 2, -2]} intensity={0.9} color={theme.forge} />
          <Suspense fallback={null}>
            <ChampionModel slug={slug} />
            <Environment preset="night" />
          </Suspense>
          {/*
            The champion is the one asset a player never sees in the arena, so
            inspecting it properly matters: drag to orbit, scroll to zoom. Idle
            auto-rotation stops the moment it is touched, which is why the spin
            lives here rather than in a useFrame the user cannot interrupt.
            Panning stays off so the model cannot be dragged out of frame.
          */}
          <OrbitControls
            makeDefault
            autoRotate
            autoRotateSpeed={0.7}
            enablePan={false}
            minDistance={2}
            maxDistance={7}
            minPolarAngle={0.25}
            maxPolarAngle={Math.PI - 0.25}
          />
        </Canvas>
      )}

      <p className="pointer-events-none absolute bottom-3 left-1/2 -translate-x-1/2 font-mono text-[9px] uppercase tracking-[0.25em] text-stone-600">
        your champion · generated by meshy-7 · drag to inspect
      </p>
    </div>
  );
}
