import { Suspense, useEffect, useMemo, useRef, useState } from "react";
import { Canvas, useFrame } from "@react-three/fiber";
import { Environment, useGLTF } from "@react-three/drei";
import { Group } from "three";
import type { Affinity } from "@relic/core";
import { fitCharacter } from "../lib/characterFit";
import { themeFor } from "../game/theme";

/**
 * Your champion.
 *
 * First person means you never see yourself in the arena, so the character
 * appears where the decision is actually made. Picking "Ember" should show an
 * ember champion turning slowly in front of you, not a word next to an emoji.
 *
 * Falls back to nothing when a model has not been generated, so the affinity
 * screen still works on a fresh clone with an empty storage directory.
 */

const CHAMPION_HEIGHT = 2.6;

function ChampionModel({ slug }: { slug: string }) {
  const pivot = useRef<Group>(null);
  const { scene } = useGLTF(`/assets/champions/${slug}/model.glb`);
  const model = useMemo(() => scene.clone(true), [scene]);
  const fit = useMemo(() => fitCharacter(model as Group, CHAMPION_HEIGHT), [model]);

  useFrame(({ clock }) => {
    if (pivot.current) pivot.current.rotation.y = Math.sin(clock.getElapsedTime() * 0.35) * 0.6;
  });

  return (
    <group ref={pivot}>
      <group position={fit.offset} scale={fit.scale}>
        {/* Concepts are framed front-on, so the mesh already faces the camera. */}
        <primitive object={model} />
      </group>
    </group>
  );
}

export function ChampionPreview({ affinity }: { affinity: Affinity }) {
  const [available, setAvailable] = useState<boolean | null>(null);
  const theme = themeFor(affinity);
  const slug = affinity === "fire" ? "ember" : affinity === "ice" ? "frost" : "storm";

  useEffect(() => {
    let cancelled = false;
    setAvailable(null);
    fetch(`/assets/champions/${slug}/model.glb`, { method: "HEAD" })
      .then((res) => !cancelled && setAvailable(res.ok))
      .catch(() => !cancelled && setAvailable(false));
    return () => {
      cancelled = true;
    };
  }, [slug]);

  if (available === false) return null;

  return (
    <div className="relative h-72 w-full border border-ash-800 bg-ash-900/40">
      {available && (
        <Canvas camera={{ position: [0, 1.3, 3.4], fov: 40 }}>
          <ambientLight intensity={0.55} />
          <directionalLight position={[3, 5, 4]} intensity={2.1} />
          <directionalLight position={[-3, 2, -2]} intensity={0.9} color={theme.forge} />
          <Suspense fallback={null}>
            <ChampionModel slug={slug} />
            <Environment preset="night" />
          </Suspense>
        </Canvas>
      )}

      <p className="absolute bottom-3 left-1/2 -translate-x-1/2 font-mono text-[9px] uppercase tracking-[0.25em] text-stone-600">
        your champion · generated by meshy-7
      </p>
    </div>
  );
}
