import { Suspense, useEffect, useMemo, useRef, useState } from "react";
import { Canvas, useFrame } from "@react-three/fiber";
import { Environment, useGLTF } from "@react-three/drei";
import { Bloom, EffectComposer } from "@react-three/postprocessing";
import { Group, Quaternion, Vector3 } from "three";
import { normalizeRelic, type RelicDNA, type WeaponClass } from "@relic/core";
import { meshSampleFrom } from "../lib/meshSample";

/**
 * The homepage argues that generated 3D belongs in a runtime, so the homepage
 * should be running some.
 *
 * Every weapon shown here was generated by the same pipeline the game uses,
 * loaded from the same cache, canonicalized by the same normalizer. Nothing is
 * a render, a screenshot, or a placeholder. That is the claim, made by
 * demonstration rather than by paragraph.
 */

interface ShowcaseRelic {
  relicId: string;
  name: string;
  dna: RelicDNA;
  modelUrl: string | null;
  status: string;
}

function SpinningRelic({
  modelUrl,
  weaponClass,
}: {
  modelUrl: string;
  weaponClass: WeaponClass;
}) {
  const pivot = useRef<Group>(null);
  const { scene } = useGLTF(modelUrl);
  const model = useMemo(() => scene.clone(true), [scene]);

  // Same canonicalization the game runs at equip time, so what the homepage
  // shows is exactly what a player would be handed.
  const canonical = useMemo(
    () => normalizeRelic(meshSampleFrom(model), weaponClass),
    [model, weaponClass],
  );

  const quaternion = useMemo(() => {
    const [x, y, z, w] = canonical.quaternion;
    return new Quaternion(x, y, z, w);
  }, [canonical]);

  const gripOffset = useMemo(() => new Vector3(...canonical.gripOffset), [canonical]);

  useFrame(({ clock }) => {
    if (!pivot.current) return;
    const t = clock.getElapsedTime();
    pivot.current.rotation.y = t * 0.35;
    pivot.current.position.y = Math.sin(t * 0.7) * 0.06;
  });

  return (
    <group ref={pivot}>
      {/*
        Canonical form puts the grip at the origin and the blade above it, so a
        camera aimed at the origin frames the handle and crops the blade.
        Dropping the relic by half a canonical length centres the weapon.
      */}
      <group position={[0, -0.9, 0]}>
        <group position={gripOffset}>
          <group quaternion={quaternion} scale={canonical.scale}>
            <primitive object={model} />
          </group>
        </group>
      </group>
    </group>
  );
}

export function TitleShowcase() {
  const [relics, setRelics] = useState<ShowcaseRelic[]>([]);
  const [index, setIndex] = useState(0);

  useEffect(() => {
    fetch("/api/debug/relics")
      .then((r) => r.json())
      .then((data: { relics: ShowcaseRelic[] }) => {
        setRelics(data.relics.filter((r) => r.status === "COMPLETE" && r.modelUrl).slice(0, 4));
      })
      .catch(() => {
        /* The title screen must still work with the API down. */
      });
  }, []);

  // Rotate through what has actually been forged. Seeing several distinct
  // weapons do the work that "one of one" cannot do in prose.
  useEffect(() => {
    if (relics.length < 2) return undefined;
    const timer = setInterval(() => setIndex((i) => (i + 1) % relics.length), 7000);
    return () => clearInterval(timer);
  }, [relics.length]);

  const current = relics[index];
  if (!current?.modelUrl) return null;

  return (
    <div className="pointer-events-none relative h-[46vh] w-full max-w-3xl">
      <Canvas camera={{ position: [2.4, 0.2, 2.4], fov: 42 }} gl={{ antialias: true }}>
        <ambientLight intensity={0.5} />
        <directionalLight position={[4, 6, 3]} intensity={2.2} />
        <directionalLight position={[-4, 2, -3]} intensity={0.8} color="#ff8c42" />
        <Suspense fallback={null}>
          <SpinningRelic modelUrl={current.modelUrl} weaponClass={current.dna.weaponClass} />
          <Environment preset="night" />
        </Suspense>
        <EffectComposer>
          <Bloom intensity={0.9} luminanceThreshold={0.7} luminanceSmoothing={0.3} mipmapBlur />
        </EffectComposer>
      </Canvas>

      {/* Provenance, stated under the object it describes. */}
      <div className="absolute bottom-0 left-1/2 -translate-x-1/2 text-center">
        <p className="font-display text-lg tracking-[0.22em] text-ember-300">
          {current.name.toUpperCase()}
        </p>
        <p className="mt-1 font-mono text-[10px] uppercase tracking-[0.22em] text-stone-600">
          {current.dna.element} · {current.dna.temperament} · {current.dna.condition} ·{" "}
          {current.dna.weaponClass}
        </p>
        <p className="mt-2 font-mono text-[9px] uppercase tracking-[0.2em] text-stone-700">
          generated by meshy-7 from a real fight · not authored by hand
        </p>
      </div>

      {relics.length > 1 && (
        <div className="absolute bottom-0 right-0 flex gap-1.5">
          {relics.map((relic, i) => (
            <span
              key={relic.relicId}
              className={
                i === index ? "h-1 w-6 bg-ember-500" : "h-1 w-6 bg-ash-700"
              }
            />
          ))}
        </div>
      )}
    </div>
  );
}
